import 'package:flutter/material.dart';
// @dart=2.9
class Product {
  final String image, title, description,shortdesc,type;
  final int? price, size, id;
  final Color? color;
  Product({
    this.id,

    required this.image,
    required this.title,
    this.price,
    required this.description,
    required this.type,
    required this.shortdesc,
    this.size,
    this.color,
  });
}

List<Product> products = [
  Product(
      id: 1,
      title: "Office Code",
      price: 20,
      size: 12,
      shortdesc:"Fashion Women’s Handbags And \nShoulder Bag Combo",
      description: dummyText,
      type:"bag",
      image: "assets/images/bag1.png",
      color: Color(0xFF9B9B9B)),
  Product(
      id: 2,
      title: "Belt Bag",
      price: 24,
      size: 8,
      shortdesc:"latest fashion 4 set Handbags\n And Shoulder Bag",
      description: dummyText,
      type:"bag",
      image: "assets/images/bag2.png",
      color: Color(0xFF2D2D2D)),
  Product(
      id: 3,
      title: "Hang Top",
      price: 24,
      size: 10,
      type:"bag",
      shortdesc:"gold and black modern work Bag",
      description: dummyText,
      image: "assets/images/bag3.png",
      color: Color(0xFF2D2D2D)),
  Product(
      id: 4,
      title: "Old Fashion",
      price: 17,
      size: 11,
      type:"bag",
      shortdesc:"Cream Color Party Wear Hand\nbag & Sling bag For Women’s",
      description: dummyText,
      image: "assets/images/bag4.png",
      color: Color(0xFFFCF5E2)),
  Product(
      id: 5,
      title: "Office Code",
      price: 25,
      size: 12,
      type:"bag",
      shortdesc:"oteawe Women Purses and Hand\nbags Casual Crossbody Shoulder",
      description: dummyText,
      image: "assets/images/bag5.png",
      color: Color(0xFFD77171)),
  Product(
    id: 6,
    title: "Office Code",
    price: 15,
    size: 12,
    type:"bag",
    shortdesc:"Fostelo Jessy Stylish Women’s \nHandbag",
    description: dummyText,
    image: "assets/images/bag6.png",
    color: Color(0xFF3F2249),),
  Product(
    id: 7,
    title: "Office Code",
    price: 19,
    size: 12,
    type:"bag",
    shortdesc: "Pu Leather Shoulder Bags For \nWomen beautiful Colour",
    description: dummyText,
    image: "assets/images/bag7.png",
    color: Color(0xFFAD9766),),
  Product(
    id: 8,
    title: "Office Code",
    price: 20,
    size: 12,
    type:"bag",
    shortdesc: "Lapis O Lupe Arancione\n Women Handbag",
    description: dummyText,
    image: "assets/images/bag8.png",
    color: Color(0xFF3B3535),),
];

String dummyText =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.";

// jewels 12
List<Product> jewels = [
  Product(
      id: 1,
      title: "Office Code",
      price: 25,
      size: 12,
      type:"jewel",
      shortdesc: "Gold rose ring",
      description: dummyText,
      image: "assets/images/jewel1.png",
      color: Color(0xFFFFC24B)),
  Product(
      id: 2,
      title: "Belt Bag",
      price: 65,
      size: 8,
      type:"jewel",
      shortdesc: "silver ring with \n3krt diamond",
      description: dummyText,
      image: "assets/images/jewel2.png",
      color: Color(0xFFE1B9C8)),
  Product(
      id: 3,
      title: "Hang Top",
      price: 14,
      size: 10,
      type:"jewel",
      shortdesc: "2 set silver rigs",
      description: dummyText,
      image: "assets/images/jewel3.png",
      color: Color(0xFFEEB4CD)),
  Product(
      id: 4,
      title: "Old Fashion",
      price: 14,
      size: 11,
      type:"jewel",
      shortdesc: "2 gold rings with \n5krt diamonds",
      description: dummyText,
      image: "assets/images/jewel4.png",
      color: Color(0xFFF8D1D1)),
  Product(
      id: 5,
      title: "Office Code",
      price: 10,
      size: 12,
      type:"jewel",
      shortdesc: "vintage gold bracelet \nwith 5krt diamonds",
      description: dummyText,
      image: "assets/images/jewel5.png",
      color: Color(0xFFFCD5C7)),
  Product(
    id: 6,
    title: "Office Code",
    price: 10,
    size: 12,
    type:"jewel",
    shortdesc: "silver and gold bracelet",
    description: dummyText,
    image: "assets/images/jewel6.png",
    color: Color(0xFFFCD5C7),),
  Product(
    id: 7,
    title: "Office Code",
    price: 100,
    size: 12,
    type:"jewel",
    shortdesc: "gold phoenix necklace \nwith red gems ",
    description: dummyText,
    image: "assets/images/jewel7.png",
    color: Color(0xFF721111),),
  Product(
    id: 8,
    title: "Office Code",
    price: 10,
    size: 12,
    type:"jewel",
    shortdesc: "simple designed love\n necklace",
    description: dummyText,
    image: "assets/images/jewel8.png",
    color: Color(0xFFEEB4CD),),
  Product(
    id: 9,
    title: "Office Code",
    price: 55,
    size: 12,
    type:"jewel",
    shortdesc: "vintage necklace royal \nemerald green gemstones",
    description: dummyText,
    image: "assets/images/jewel9.png",
    color: Color(0xFF2F5D23),),
  Product(
    id: 10,
    title: "Office Code",
    price: 42,
    size: 12,
    type:"jewel",
    shortdesc: "gold earring set with diamonds",
    description: dummyText,
    image: "assets/images/jewel10.png",
    color: Color(0xFFF8D1D1),),
  Product(
    id: 11,
    title: "Office Code",
    price: 25,
    size: 12,
    type:"jewel",
    shortdesc: "silver earrings with \nsky blue gemstone",
    description: dummyText,
    image: "assets/images/jewel11.png",
    color: Color(0xFF6497BE),),
  Product(
    id: 12,
    title: "Office Code",
    price: 10,
    size: 12,
    type:"jewel",
    shortdesc: "simple silver rounded earring",
    description: dummyText,
    image: "assets/images/jewel12.png",
    color: Color(0xFFEEB4CD),),
];


List<Product> foots = [
  Product(
      id: 1,
      title: "Office Code",
      price: 20,
      size: 12,
      type:"shoes",
      shortdesc: "cream colored high heels",
      description: dummyText,
      image: "assets/images/foot4.png",
      color: Color(0xFFE8E8C0)),
  Product(
      id: 2,
      title: "Belt Bag",
      price: 50,
      size: 8,
      type:"shoes",
      shortdesc: "winter ankle boot with\n fur texture",
      description: dummyText,
      image: "assets/images/foot7.png",
      color: Color(0xFF6E6D6D)),
  Product(
      id: 3,
      title: "Hang Top",
      price: 9,
      size: 10,
      type:"shoes",
      shortdesc: "simple evey day jelly\n shoes",
      description: dummyText,
      image: "assets/images/foot3.png",
      color: Color(0xFF378DC0)),
  Product(
      id: 4,
      title: "Old Fashion",
      price: 25,
      size: 11,
      type:"shoes",
      shortdesc: "sexy red peep toe shoes",
      description: dummyText,
      image: "assets/images/foot2.png",
      color: Color(0xFFDC5656)),
  Product(
      id: 5,
      title: "Office Code",
      price: 55,
      size: 12,
      type:"shoes",
      shortdesc: "chery blossom ankle straps\n high heels",
      description: dummyText,
      image: "assets/images/foot5.png",
      color: Color(0xFFEFA9A9)),
  Product(
    id: 6,
    title: "Office Code",
    price: 30,
    size: 12,
    type:"shoes",
    shortdesc: "emerald colored stiletto heels",
    description: dummyText,
    image: "assets/images/foot6.png",
    color: Color(0xFF0E5A6C),),
  Product(
    id: 7,
    title: "Office Code",
    price: 14,
    size: 12,
    type:"shoes",
    shortdesc: "comfy beach bow sandals",
    description: dummyText,
    image: "assets/images/foot1.png",
    color: Color(0xFFAEE185),),
  Product(
    id: 8,
    title: "Office Code",
    price: 50,
    size: 12,
    type:"shoes",
    shortdesc: "dark red thigh high boots",
    description: dummyText,
    image: "assets/images/foot8.png",
    color: Color(0xFF4B1010),),
  Product(
    id: 9,
    title: "Office Code",
    price: 44,
    size: 12,
    type:"shoes",
    shortdesc: "party cream platforms",
    description: dummyText,
    image: "assets/images/foot9.png",
    color: Color(0xFFFFF6B3),),
  Product(
    id: 10,
    title: "Office Code",
    price: 25,
    size: 12,
    type:"shoes",
    shortdesc: "high wedge ankle straps heels",
    description: dummyText,
    image: "assets/images/foot10.png",
    color: Color(0xFF3A4354),),

];


List<Product> dresses = [
  Product(
      id: 1,
      title: "Office Code",
      price: 200,
      size: 12,
      type:"dress",
      shortdesc: "islamic indian wedding dress",
      description: dummyText,
      image: "assets/images/dress1.png",
      color: Color(0xFFE5C35F)),
  Product(
      id: 2,
      title: "Belt Bag",
      price: 150,
      size: 8,
      type:"dress",
      shortdesc: "casual outing muslim dress",
      description: dummyText,
      image: "assets/images/dress2.png",
      // color: Color(0xFF9A9A9A),
      color: Color(0xFFEDEDED)),
  Product(
      id: 3,
      title: "Hang Top",
      price: 500,
      size: 10,
      type:"dress",
      shortdesc: "latest red gems dress",
      description: dummyText,
      image: "assets/images/dress3.png",
      color: Color(0xFFB70050)),
  Product(
      id: 4,
      title: "Old Fashion",
      price: 650,
      size: 11,
      type:"dress",
      shortdesc: "princess gold wedding dress",
      description: dummyText,
      image: "assets/images/dress4.png",
      color: Color(0xFFEAE78A)),
  Product(
      id: 5,
      title: "Office Code",
      price: 400,
      size: 12,
      type:"dress",
      shortdesc: "red carpet blue dress",
      description: dummyText,
      image: "assets/images/dress5.png",
      color: Color(0xFF1573AD)),
  Product(
    id: 6,
    title: "Office Code",
    price: 600,
    size: 12,
    type:"dress",
    shortdesc: "light colored twin ball gowns",
    description: dummyText,
    image: "assets/images/dress6.png",
    color: Color(0xFFF7E0E3),),
  Product(
    id: 7,
    title: "Office Code",
    price: 350,
    size: 12,
    type:"dress",
    shortdesc: "pink and cream bride\n maids gowns",
    description: dummyText,
    image: "assets/images/dress7.png",
    color: Color(0xF4FAAEAE),),

];